name = "do-worker"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[[durable_objects.bindings]]
name = "MY_DO"
class_name = "MyDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["MyDurableObject"]
